name: Deploy Application

on:
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Trigger Docker Build and Push workflow using repository_dispatch
      - name: Trigger Docker Build and Push
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"trigger-build-push-docker"}'

      # Step 3: Trigger Terraform Plan and Apply workflow using repository_dispatch
      - name: Trigger Terraform Deploy
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"trigger-terraform-deploy"}'
