name: Terraform Plan and Apply

on:
  workflow_disptach:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 3: Configure AWS credentials for Terraform
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      # Step 4: Run terraform init to initialize the working directory
      - name: Terraform Init
        run: terraform init

      # Step 5: Run terraform plan to preview the changes
      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars  # Change dev.tfvars if needed for different environments

      # Step 6: Apply the Terraform changes (deploy)
      - name: Terraform Apply
        run: terraform apply -var-file=dev.tfvars -auto-approve  # Change dev.tfvars if needed for different environments

